services:
  - postgresql
dist: trusty
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - travis_wait 30 yarn install
  - psql -c 'create database myDiary;' -U postgres
  - travis_wait npm install
script:
  - node build/models/database.js
  - ./node_modules/mocha/bin/mocha  --exit
after_success:
  - npm run coveralls