services:
  - postgresql
dist: trusty
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
postgres:
  adapter: postgresql
  database: myDiary
  username: postgres
before_script:
  - travis_wait 30 yarn install
  - psql -c 'create database myDiary;' -U postgres
  - cp database.yml.travis config/database.yml
  - travis_wait npm install
  - node build/models/database.js
script:
  - ./node_modules/mocha/bin/mocha  --exit
after_success:
  - npm run coveralls