services:
  - postgresql
dist: trusty
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  postgresql: "9.5"
before_script:
  - travis_wait 30 yarn install
  - psql -c 'create database myDiary;' -U postgres
  - psql -c "CREATE USER andela WITH PASSWORD 'andela';" -U postgres
  - travis_wait npm install
  - psql -U postgres -d travis -f database/myDiary.sql
script:
  - ./node_modules/mocha/bin/mocha  --exit
after_success:
  - npm run coveralls